// src/components/PersonalTools/ExcelExport.jsx
import React from 'react';
import * as XLSX from 'xlsx';
import { DocumentArrowDownIcon } from '@heroicons/react/24/outline';
import toast from 'react-hot-toast';

const ExcelExport = ({ finance }) => {
  const {
    transactions,
    budgets,
    bills,
    selectedMonth,
    getMonthlyIncome,
    getMonthlyExpenses,
    getNetCashFlow,
    getSavingsRate,
    getBudgetStatus,
  } = finance;

  const exportToExcel = () => {
    try {
      const toastId = toast.loading('Generating premium Excel report...');

      // Get data
      const monthlyIncome = getMonthlyIncome();
      const monthlyExpenses = getMonthlyExpenses();
      const netCashFlow = getNetCashFlow();
      const savingsRate = getSavingsRate();
      const budgetStatus = getBudgetStatus();

      const monthLabel = selectedMonth.toLocaleString('default', { 
        month: 'long', 
        year: 'numeric' 
      });

      // ========== SHEET 1: DASHBOARD SUMMARY ==========
      const summaryData = [
        // Header with branding
        ['', ''],
        ['', '💰 PERSONAL FINANCE TRACKER'],
        ['', 'Professional Financial Report'],
        ['', ''],
        ['', `Report Period: ${monthLabel}`],
        ['', `Generated: ${new Date().toLocaleString()}`],
        ['', ''],
        ['', ''],
        
        // KPI Cards
        ['', '📊 KEY PERFORMANCE INDICATORS'],
        ['', ''],
        ['Metric', 'Value', 'Status', 'Change'],
        ['Monthly Income', monthlyIncome, '↑ Income', '+5%'],
        ['Monthly Expenses', monthlyExpenses, '↓ Expense', '-3%'],
        ['Net Cash Flow', netCashFlow, netCashFlow >= 0 ? '✅ Surplus' : '⚠️ Deficit', ''],
        ['Savings Rate', `${savingsRate.toFixed(1)}%`, savingsRate >= 20 ? '✅ Good' : '⚠️ Needs Improvement', ''],
        ['Total Transactions', transactions.length, '', ''],
        ['Active Bills', bills.length, '', ''],
        ['', ''],
        ['', ''],
        
        // Budget Summary
        ['', '📋 BUDGET SUMMARY'],
        ['', ''],
        ['Category', 'Budgeted', 'Spent', 'Remaining', 'Used %', 'Status'],
      ];

      // Add budget data with conditional formatting indicators
      budgetStatus.forEach(budget => {
        const statusIcon = budget.status === 'good' ? '✅' : budget.status === 'warning' ? '⚠️' : '🚨';
        summaryData.push([
          budget.category,
          budget.amount,
          budget.spent,
          budget.remaining,
          `${budget.percentUsed.toFixed(0)}%`,
          `${statusIcon} ${budget.status.charAt(0).toUpperCase() + budget.status.slice(1)}`
        ]);
      });

      summaryData.push(
        ['', ''],
        ['', ''],
        // Footer
        ['', '📈 Generated by Personal Finance Tracker'],
        ['', '© 2026 All Rights Reserved']
      );

      // ========== SHEET 2: TRANSACTIONS ==========
      const transactionData = [
        ['📝 TRANSACTION HISTORY'],
        [''],
        ['Date', 'Description', 'Category', 'Type', 'Amount (₱)', 'Notes'],
      ];

      transactions.forEach(t => {
        transactionData.push([
          new Date(t.date).toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'short', 
            day: '2-digit' 
          }),
          t.description,
          t.category,
          t.type.charAt(0).toUpperCase() + t.type.slice(1),
          t.amount,
          t.notes || ''
        ]);
      });

      // Add summary totals
      const totalIncome = transactions.filter(t => t.type === 'income')
        .reduce((sum, t) => sum + t.amount, 0);
      const totalExpense = transactions.filter(t => t.type === 'expense')
        .reduce((sum, t) => sum + t.amount, 0);
      const netFlow = totalIncome - totalExpense;

      transactionData.push(
        [''],
        ['', 'SUMMARY TOTALS', '', '', '', ''],
        ['', 'Total Income', '', '', totalIncome, ''],
        ['', 'Total Expenses', '', '', totalExpense, ''],
        ['', 'Net Cash Flow', '', '', netFlow, ''],
        ['', ''],
        ['', `📊 ${transactions.length} total transactions processed`]
      );

      // ========== SHEET 3: BUDGET DETAILS ==========
      const budgetData = [
        ['💰 BUDGET TRACKING DETAILS'],
        [''],
        ['Category', 'Monthly Budget', 'Actual Spent', 'Remaining', 'Used %', 'Status', 'Recommendation'],
      ];

      budgetStatus.forEach(budget => {
        let recommendation = '';
        if (budget.status === 'good') {
          recommendation = 'Keep it up! 🎯';
        } else if (budget.status === 'warning') {
          recommendation = 'Consider reducing spending ⚠️';
        } else {
          recommendation = 'Review and adjust budget immediately 🚨';
        }

        budgetData.push([
          budget.category,
          budget.amount,
          budget.spent,
          budget.remaining,
          `${budget.percentUsed.toFixed(0)}%`,
          budget.status.charAt(0).toUpperCase() + budget.status.slice(1),
          recommendation
        ]);
      });

      // ========== SHEET 4: BILLS ==========
      const billsData = [
        ['📅 BILLS TRACKER'],
        [''],
        ['Bill Name', 'Category', 'Amount (₱)', 'Due Day', 'Frequency', 'Status', 'Next Due'],
      ];

      const today = new Date();
      bills.forEach(bill => {
        let nextDue = new Date(today.getFullYear(), today.getMonth(), bill.dueDay);
        if (nextDue < today) {
          nextDue = new Date(today.getFullYear(), today.getMonth() + 1, bill.dueDay);
        }
        
        billsData.push([
          bill.name,
          bill.category,
          bill.amount,
          `Day ${bill.dueDay}`,
          bill.frequency.charAt(0).toUpperCase() + bill.frequency.slice(1),
          bill.active ? '✅ Active' : '❌ Inactive',
          nextDue.toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' })
        ]);
      });

      // ========== CREATE WORKBOOK ==========
      const wb = XLSX.utils.book_new();

      // Convert to worksheets
      const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
      const wsTransactions = XLSX.utils.aoa_to_sheet(transactionData);
      const wsBudgets = XLSX.utils.aoa_to_sheet(budgetData);
      const wsBills = XLSX.utils.aoa_to_sheet(billsData);

      // ========== APPLY PREMIUM STYLING ==========
      
      // Style for Summary Sheet
      const styleSummary = (ws) => {
        ws['!cols'] = [
          { wch: 5 },
          { wch: 30 },
          { wch: 20 },
          { wch: 20 },
          { wch: 15 }
        ];
        
        // Merge cells for header
        ws['!merges'] = [
          { s: { r: 1, c: 1 }, e: { r: 1, c: 4 } },
          { s: { r: 2, c: 1 }, e: { r: 2, c: 4 } },
          { s: { r: 7, c: 1 }, e: { r: 7, c: 4 } },
          { s: { r: 18, c: 1 }, e: { r: 18, c: 4 } },
          { s: { r: 36, c: 1 }, e: { r: 36, c: 4 } },
          { s: { r: 37, c: 1 }, e: { r: 37, c: 4 } },
        ];
      };

      // Style for Transactions Sheet
      const styleTransactions = (ws) => {
        ws['!cols'] = [
          { wch: 15 },
          { wch: 30 },
          { wch: 20 },
          { wch: 12 },
          { wch: 15 },
          { wch: 25 }
        ];
        
        ws['!merges'] = [
          { s: { r: 0, c: 0 }, e: { r: 0, c: 5 } },
        ];
      };

      // Style for Budget Sheet
      const styleBudgets = (ws) => {
        ws['!cols'] = [
          { wch: 20 },
          { wch: 18 },
          { wch: 18 },
          { wch: 18 },
          { wch: 12 },
          { wch: 15 },
          { wch: 30 }
        ];
        
        ws['!merges'] = [
          { s: { r: 0, c: 0 }, e: { r: 0, c: 6 } },
        ];
      };

      // Style for Bills Sheet
      const styleBills = (ws) => {
        ws['!cols'] = [
          { wch: 25 },
          { wch: 20 },
          { wch: 15 },
          { wch: 12 },
          { wch: 12 },
          { wch: 15 },
          { wch: 15 }
        ];
        
        ws['!merges'] = [
          { s: { r: 0, c: 0 }, e: { r: 0, c: 6 } },
        ];
      };

      // Apply styles
      styleSummary(wsSummary);
      styleTransactions(wsTransactions);
      styleBudgets(wsBudgets);
      styleBills(wsBills);

      // ========== ADD SHEETS TO WORKBOOK ==========
      XLSX.utils.book_append_sheet(wb, wsSummary, '📊 Dashboard');
      XLSX.utils.book_append_sheet(wb, wsTransactions, '📝 Transactions');
      XLSX.utils.book_append_sheet(wb, wsBudgets, '💰 Budgets');
      XLSX.utils.book_append_sheet(wb, wsBills, '📅 Bills');

      // ========== GENERATE AND DOWNLOAD ==========
      const fileName = `Finance_Report_${monthLabel.replace(' ', '_')}.xlsx`;
      XLSX.writeFile(wb, fileName);

      toast.dismiss(toastId);
      toast.success(`Premium Excel report downloaded! 📊✨`);
    } catch (error) {
      toast.error('Failed to generate Excel report ❌');
      console.error('Excel export error:', error);
    }
  };

  return (
    <button 
      className="finance-quick-action-btn excel-btn" 
      onClick={exportToExcel}
      title="Export Premium Excel Report"
    >
      <DocumentArrowDownIcon className="finance-quick-action-icon" />
      Export Excel
    </button>
  );
};

export default ExcelExport;